[package]
name = "csv"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
encoding_rs = "0.8.35"
memchr = "2.7.4"
tokio = { version = "1.42.0", features = ["full"] }
tokio-stream = "0.1.17"
macros = { path = "./macros" }
